# Generated by Django 6.0.4 on 2026-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('ingredients_raw', models.TextField(blank=True, null=True)),
                ('ingredients_clean', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('total_time_mins', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('app_category', models.CharField(blank=True, max_length=200, null=True)),
                ('regional_cuisine', models.CharField(blank=True, max_length=200, null=True)),
                ('protein_class', models.CharField(blank=True, max_length=100, null=True)),
                ('fat_class', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
