# Generated by Django 6.0.4 on 2026-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDisposalGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=255)),
                ('steps', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('source_link', models.URLField(blank=True)),
            ],
        ),
    ]
